TerjeSaetherWeb/Controllers/FrontPageBoxesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TerjeSaetherWeb.Models;

namespace TerjeSaetherWeb.Controllers
{
    public class FrontPageBoxesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: FrontPageBoxes
        public ActionResult Index()
        {
            return View(db.FrontPageBoxes.ToList());
        }

        // GET: FrontPageBoxes/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FrontPageBox frontPageBox = db.FrontPageBoxes.Find(id);
            if (frontPageBox == null)
            {
                return HttpNotFound();
            }
            return View(frontPageBox);
        }

        // GET: FrontPageBoxes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: FrontPageBoxes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Title,Content")] FrontPageBox frontPageBox)
        {
            if (ModelState.IsValid)
            {
                frontPageBox.Id = Guid.NewGuid();
                db.FrontPageBoxes.Add(frontPageBox);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(frontPageBox);
        }

        // GET: FrontPageBoxes/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FrontPageBox frontPageBox = db.FrontPageBoxes.Find(id);
            if (frontPageBox == null)
            {
                return HttpNotFound();
            }
            return View(frontPageBox);
        }

        // POST: FrontPageBoxes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Title,Content")] FrontPageBox frontPageBox)
        {
            if (ModelState.IsValid)
            {
                db.Entry(frontPageBox).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(frontPageBox);
        }

        // GET: FrontPageBoxes/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FrontPageBox frontPageBox = db.FrontPageBoxes.Find(id);
            if (frontPageBox == null)
            {
                return HttpNotFound();
            }
            return View(frontPageBox);
        }

        // POST: FrontPageBoxes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            FrontPageBox frontPageBox = db.FrontPageBoxes.Find(id);
            db.FrontPageBoxes.Remove(frontPageBox);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TerjeSaetherWeb/Controllers/SongsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TerjeSaetherWeb.Models;

namespace TerjeSaetherWeb.Controllers
{
    public class SongsController : Controller
    {
        private ApplicationDbContext _db = new ApplicationDbContext();
        private HelperMethods _helperMethods = new HelperMethods();

        // GET: Songs
        public ActionResult Index()
        {
            return View(_db.Song.ToList());
        }

        // GET: Songs/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Song song = _db.Song.Find(id);
            if (song == null)
            {
                return HttpNotFound();
            }
            return View(song);
        }

        // GET: Songs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Songs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Title,Comment,AudioUrl,ImageUrl,ShowOnFrontpage")] Song song)
        {
            //var request = HttpContext.Request;
            HttpRequest httpRequest = System.Web.HttpContext.Current.Request;
            var filePath = "/Audio";
            
            HttpPostedFile imageFile = null;
            HttpPostedFile audioFile = null;
           
            if (httpRequest.Files.Count > 0)
            {
                imageFile = httpRequest.Files[0];
                audioFile = httpRequest.Files[1];
            }
            

            if (ModelState.IsValid)
            {
                var filenames = new List<string> { song.Title };
                
                song.SongId = Guid.NewGuid();
                song.Timestamp = DateTime.Now;

                var imageId = Guid.NewGuid();
                song.Image = new Image
                {
                    ImageId = imageId,
                    Data = _helperMethods.ConvertToByteArray(imageFile.InputStream),
                    Timestamp = DateTime.Now,
                    ImageUrl = Url.RouteUrl("Images", new { id = imageId })
                };

                bool isSaved = _helperMethods.SaveUploadedAudioFile(audioFile, filePath, song.Title);

                if (isSaved)
                {
                    song.AudioUrl = filePath + song.Title;
                }

                _db.Song.Add(song);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(song);
        }

        // GET: Songs/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Song song = _db.Song.Find(id);
            if (song == null)
            {
                return HttpNotFound();
            }
            return View(song);
        }

        // POST: Songs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "SongId,Title,Timestamp,AudioUrl")] Song song)
        {
            if (ModelState.IsValid)
            {
                _db.Entry(song).State = EntityState.Modified;
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(song);
        }

        // GET: Songs/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Song song = _db.Song.Find(id);
            if (song == null)
            {
                return HttpNotFound();
            }
            return View(song);
        }

        // POST: Songs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            Song song = _db.Song.Find(id);
            _db.Song.Remove(song);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TerjeSaetherWeb/Views/Shared/_AdminSongsMenu.cshtml
<div class="row">
    <div class="col-md-4">@Html.ActionLink("Add Song", "Create", "Songs")</div>
    <div class="col-md-4">@Html.ActionLink("Edit Song", "Edit", "Songs")</div>
    <div class="col-md-4">@Html.ActionLink("Delete Song", "Delete", "Songs")</div>
</div>

TerjeSaetherWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand hidden" })
                <div class="col-md-7">
                    @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand hidden" })
                    <img src="~/Images/Terje_logo_header_H150.png" class="navbar-logo img-responsive" alt="Alternate Text" />
                    @Html.Partial("_LoginPartial")
                </div>
            </div>
            <div class="navbar-collapse collapse">
               
                    
                
                <ul class="nav navbar-nav navbar-right">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    @*<li>@Html.ActionLink("Music", "About", "Home")</li>*@
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Music <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="#">Releases</a></li>
                            <li>@Html.ActionLink("Album", "Album", "Home")</li>
                            <li><a href="#">Blog</a></li>
                        </ul>
                    </li>

                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Admin <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Soundcloudlinks", "Index", "Soundcloudlinks")</li>
                            <li><a href="#">Releases</a></li>
                            <li>@Html.ActionLink("Frontbox", "Index", "FrontPageBoxes")</li>
                            <li>@Html.ActionLink("Songs", "Index", "Songs")</li>
                            <li><a href="#">Blog</a></li>                            
                        </ul>
                    </li>
                    <li>@Html.ActionLink("Web Dev", "About", "Home")</li>
                    @*<li>@Html.ActionLink("Discography", "About", "Home")</li>*@
                    <li>@Html.ActionLink("About", "Contact", "Home")</li>
                </ul>
                
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Terje Saether</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>